name: Code Analysis

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '0 9 * * *'

jobs:
  code_analysis:
    name: "PHP ${{ matrix.php }}: ${{ matrix.actions.name }}"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['8.3']

        actions:
          - name: ECS
            run: "composer ecs:check"

          - name: PHPStan
            run: "composer phpstan"

          - name: Rector
            run: "composer rector:check"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      - run: ${{ matrix.actions.run }}
